In [1]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]

anh_xa = zip(thu_tu, mon_hoc, diem_so)
anh_xa_list = list(anh_xa)
print("Kết quả ghép các danh sách:")
print(anh_xa_list)
print("\nChi tiết từng môn:")
for tt, mon, diem in zip(thu_tu, mon_hoc, diem_so):
    print(f"Thứ tự: {tt}, Môn: {mon}, Điểm: {diem}")

Kết quả ghép các danh sách:
[(2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7)]

Chi tiết từng môn:
Thứ tự: 2, Môn: ToanCC, Điểm: 10
Thứ tự: 3, Môn: DSTT, Điểm: 9
Thứ tự: 4, Môn: ToanRR, Điểm: 8
Thứ tự: 1, Môn: LaptrinhCB, Điểm: 7


In [3]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
tap_hop = set(anh_xa)
print("Tập hợp các phần tử:")
for item in tap_hop:
    print(item)

Tập hợp các phần tử:
(2, 'ToanCC', 10)
(3, 'DSTT', 9)
(1, 'LaptrinhCB', 7)
(4, 'ToanRR', 8)


In [4]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
lay_TT, lay_monhoc, lay_diem = zip(*anh_xa)
print("Danh sách môn học sau khi phân rã:")
print(lay_monhoc)
print("\nDanh sách thứ tự:")
print(lay_TT)
print("\nDanh sách điểm số:")
print(lay_diem)

Danh sách môn học sau khi phân rã:
('ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB')

Danh sách thứ tự:
(2, 3, 4, 1)

Danh sách điểm số:
(10, 9, 8, 7)


In [21]:
from sympy import Symbol, symbols, expand

# Khởi tạo biến symbol x, y
x = Symbol('x')
y = Symbol('y')

# Ví dụ 1: Phép cộng biểu thức
s = x * y + y * x
print("s =", s)

# Ví dụ 2: Phép nhân với biểu thức có cộng bên trong
p = x * (x + 2 * x)
print("p =", p)

# Ví dụ 3: Biểu thức không được tự động khai triển (expand)
p = (x + 2) * (y + 3)
print("p =", p)

# Ví dụ 4: Biểu thức phức hợp chưa khai triển
p = (x + 2) * (y + 3) + (x + 2) * (x - 3)
print("p chưa expand =", p)

# Ví dụ 5: Biểu thức được SymPy tự động đơn giản hóa
p = x * (-x + 2 * x - x)
print("p đơn giản =", p)

# Ví dụ 6: Sử dụng expand() để khai triển biểu thức
p = (x + 2) * (y + 3)
p_expanded = p.expand()
print("p sau khi expand =", p_expanded)

# Bonus: Khởi tạo nhiều biến cùng lúc
a, b, c = symbols('a b c')
q = a**2 + b*c - c/a
print("Biểu thức q =", q)


s = 2*x*y
p = 3*x**2
p = (x + 2)*(y + 3)
p chưa expand = (x - 3)*(x + 2) + (x + 2)*(y + 3)
p đơn giản = 0
p sau khi expand = x*y + 3*x + 2*y + 6
Biểu thức q = a**2 + b*c - c/a


In [22]:
from sympy import Symbol, sin, cos, simplify

x = Symbol('x')
y = Symbol('y')

bt = sin(x)*cos(y) + cos(x)*sin(y)
bt_moi = simplify(bt)
print(bt_moi)


sin(x + y)


In [23]:
>>> bt_moi
sin(x + y)


sin(x + y)

In [5]:
#Bài tập 1
from sympy import Symbol, solve
x = Symbol('x')
bieuthuc = x + 3 - 5
nghiem = solve(bieuthuc)
print("Nghiệm của phương trình x + 3 - 5 = 0 là:")
print(nghiem)

Nghiệm của phương trình x + 3 - 5 = 0 là:
[2]


In [6]:
from sympy import Symbol, solve
x = Symbol('x')
bieuthuc = x**2 + 3 - 5
nghiemx = solve(bieuthuc)
print("Danh sách các nghiệm của phương trình x^2 - 2 = 0:")
print("nghiemx =", nghiemx)
print("nghiemx[0] =", nghiemx[0])
print("nghiemx[1] =", nghiemx[1])

Danh sách các nghiệm của phương trình x^2 - 2 = 0:
nghiemx = [-sqrt(2), sqrt(2)]
nghiemx[0] = -sqrt(2)
nghiemx[1] = sqrt(2)


In [7]:
#Bài tập 2
from sympy import Symbol, solve
x = Symbol('x')
ptb2 = x**2 + 9*x + 8
nghiem = solve(ptb2, dict=True)
print("Nghiệm của phương trình x^2 + 9x + 8 = 0:")
print(nghiem)


Nghiệm của phương trình x^2 + 9x + 8 = 0:
[{x: -8}, {x: -1}]


In [8]:
from sympy import Symbol, solve
x = Symbol('x')
ptb2 = x**2 + x + 10
nghiemx = solve(ptb2, dict=True)
print("Nghiệm của phương trình x^2 + x + 10 = 0:")
print(nghiemx)

Nghiệm của phương trình x^2 + x + 10 = 0:
[{x: -1/2 - sqrt(39)*I/2}, {x: -1/2 + sqrt(39)*I/2}]


In [9]:
#Bài 3
from sympy import Symbol, solve
x = Symbol('x')
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
ptb2 = a*x**2 + b*x + c
nghiem = solve(ptb2, x, dict=True)
print("Nghiệm của phương trình ax^2 + bx + c = 0:")
print(nghiem)

Nghiệm của phương trình ax^2 + bx + c = 0:
[{x: (-b - sqrt(-4*a*c + b**2))/(2*a)}, {x: (-b + sqrt(-4*a*c + b**2))/(2*a)}]


In [10]:
#hàm solve
from sympy import Symbol, solve
x = Symbol('x')
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
pt = a*x + b - c
nghiem = solve(pt, x, dict=True)
print("Nghiệm của phương trình ax + b - c = 0:")
print(nghiem)
nghiem_list = solve(pt, x)
print("\nNghiệm dạng danh sách (dict=False):")
print(nghiem_list)

Nghiệm của phương trình ax + b - c = 0:
[{x: (-b + c)/a}]

Nghiệm dạng danh sách (dict=False):
[(-b + c)/a]


In [11]:
#Bài 4
from sympy import Symbol, solve
x = Symbol('x')
y = Symbol('y')
pt1 = 2*x + 3*y - 12
pt2 = 3*x - 2*y - 5
nghiem = solve((pt1, pt2), dict=True)
print("Nghiệm của hệ phương trình:")
print(nghiem)

Nghiệm của hệ phương trình:
[{x: 3, y: 2}]


In [13]:
from sympy import Symbol, solve
x = Symbol('x')
y = Symbol('y')
pt1 = 2*x + 3*y - 12
pt2 = 3*x - 2*y - 5
nghiem = solve((pt1, pt2), dict=True)
nghiem = nghiem[0]
ket_qua_pt1 = pt1.subs({x: nghiem[x], y: nghiem[y]})
ket_qua_pt2 = pt2.subs({x: nghiem[x], y: nghiem[y]})
print("Nghiệm của hệ phương trình:", nghiem)
print("Giá trị của pt1 sau khi thay nghiệm x = {}, y = {}:".format(nghiem[x], nghiem[y]))
print(ket_qua_pt1)
print("Giá trị của pt2 sau khi thay nghiệm x = {}, y = {}:".format(nghiem[x], nghiem[y]))
print(ket_qua_pt2)

Nghiệm của hệ phương trình: {x: 3, y: 2}
Giá trị của pt1 sau khi thay nghiệm x = 3, y = 2:
0
Giá trị của pt2 sau khi thay nghiệm x = 3, y = 2:
0


In [17]:
#Bài 5
import numpy as np

# === Phần 1: Ma trận và vector ===
print("=== Phần 1: Ma trận và vector ===")
M1 = np.array([[9, 12], [23, 30]])
print("M1:")
print(M1)

u = np.array([2, 1])
tichM1u = M1.dot(u)
print("M1.dot(u):")
print(tichM1u)
print("Giải thích: M1 * u = [9*2 + 12*1, 23*2 + 30*1] = [30, 76]")

tichuM1 = u.dot(M1)
print("u.dot(M1):")
print(tichuM1)
print("Giải thích: u * M1 = [2*9 + 1*23, 2*12 + 1*30] = [41, 54]")

print("np.dot(M1, u):")
print(np.dot(M1, u))
print("Giải thích: Tương đương M1.dot(u) = [30, 76]")

print("np.dot(u, M1):")
print(np.dot(u, M1))
print("Giải thích: Tương đương u.dot(M1) = [41, 54]")

# === Phần 2: Các ma trận ===
print("\n=== Phần 2: Các ma trận ===")
mat1 = np.zeros([5, 5])
print("mat1:")
print(mat1)
print("Giải thích: Ma trận toàn số 0, kích thước 5x5")

mat2 = np.ones([5, 5])
print("mat2:")
print(mat2)
print("Giải thích: Ma trận toàn số 1, kích thước 5x5")

mat3 = mat1 + 2 * mat2
print("mat3:")
print(mat3)
print("Giải thích: Mỗi phần tử trong mat3 = 0 + 2*1 = 2")

mat4 = mat3
mat3[3][2] = 10
print("mat3 sau khi thay đổi phần tử [3][2] = 10:")
print(mat3)
print("mat4 (tham chiếu cùng mat3 nên cũng thay đổi):")
print(mat4)

mat5 = np.copy(mat3)
mat3[3][2] = 20  # Thay đổi tiếp
print("mat3 sau khi thay đổi phần tử [3][2] = 20:")
print(mat3)
print("mat4 (cũng bị thay đổi):")
print(mat4)
print("mat5 (sao chép độc lập, vẫn giữ giá trị cũ là 10):")
print(mat5)

mat6 = np.empty([4, 5])
print("mat6:")
print(mat6)
print("Giải thích: Ma trận chưa được khởi tạo giá trị rõ ràng, chứa dữ liệu rác")

mat7 = np.identity(4)
print("mat7:")
print(mat7)
print("Giải thích: Ma trận đơn vị 4x4")

mat8 = np.random.random([4, 5])
print("mat8:")
print(mat8)
print("Giải thích: Ma trận 4x5 chứa giá trị ngẫu nhiên trong [0.0, 1.0)")
## Vì sao mất 8 là ma trận 4x5 gồm các số thực ngẫu nhiên trong khoảng [0.0, 1.0), được sinh bởi hàm np.random.random([4,5]). Mỗi lần chạy sẽ ra giá trị khác nhau.
mat8 = np.random.random([4, 5])
print(mat8)



=== Phần 1: Ma trận và vector ===
M1:
[[ 9 12]
 [23 30]]
M1.dot(u):
[30 76]
Giải thích: M1 * u = [9*2 + 12*1, 23*2 + 30*1] = [30, 76]
u.dot(M1):
[41 54]
Giải thích: u * M1 = [2*9 + 1*23, 2*12 + 1*30] = [41, 54]
np.dot(M1, u):
[30 76]
Giải thích: Tương đương M1.dot(u) = [30, 76]
np.dot(u, M1):
[41 54]
Giải thích: Tương đương u.dot(M1) = [41, 54]

=== Phần 2: Các ma trận ===
mat1:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Giải thích: Ma trận toàn số 0, kích thước 5x5
mat2:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Giải thích: Ma trận toàn số 1, kích thước 5x5
mat3:
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
Giải thích: Mỗi phần tử trong mat3 = 0 + 2*1 = 2
mat3 sau khi thay đổi phần tử [3][2] = 10:
[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat4 (tham chiếu cùng mat3 nên cũ

In [20]:
#Câu 6
import numpy as np


A = np.array([  # Cháy rừng
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [3, 3, 3, 3],
    [5, 5, 5, 5],
    [9, 9, 9, 9]
])

B = np.array([  # Lũ quét
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [4, 4, 4, 4],
    [8, 8, 8, 8]
])

C = np.array([  # Sạt lở núi
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [5, 5, 5, 5]
])

D = np.array([  # Bệnh dịch
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [3, 3, 3, 3],
    [5, 5, 5, 5]
])

E = np.array([  # Lộ bí mật
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [5, 5, 5, 5]
])

# Ma trận cấp độ nguy cơ tại mỗi vị trí tương ứng
L1 = np.array([
    [3, 2, 1, 2],
    [3, 2, 1, 0],
    [1, 2, 3, 1]
])

L2 = np.array([
    [2, 3, 0, 0],
    [2, 2, 2, 2],
    [3, 3, 3, 3]
])

L3 = np.array([
    [2, 1, 2, 3],
    [0, 0, 0, 0],
    [1, 1, 1, 1]
])

L4 = np.array([
    [0, 0, 0, 0],
    [1, 2, 3, 4],
    [0, 0, 0, 0]
])

L5 = np.array([
    [1, 2, 1, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])

TONG = A[L1] + B[L2] + C[L3] + D[L4] + E[L5]
print("=== Ma trận tổng nguy cơ ===")
print(TONG)
an_toan = TONG <= 5
print("\n=== Vị trí an toàn (True = an toàn) ===")
print(an_toan)



=== Ma trận tổng nguy cơ ===
[[[10 10 10 10]
  [10 10 10 10]
  [ 4  4  4  4]
  [ 6  6  6  6]]

 [[ 8  8  8  8]
  [ 6  6  6  6]
  [ 6  6  6  6]
  [ 7  7  7  7]]

 [[ 6  6  6  6]
  [ 8  8  8  8]
  [10 10 10 10]
  [ 6  6  6  6]]]

=== Vị trí an toàn (True = an toàn) ===
[[[False False False False]
  [False False False False]
  [ True  True  True  True]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]
  [False False False False]]]
