In [1]:
#Câu 2
from sympy import symbols, solve, integrate, ln

# Vấn đề 1
x, y = symbols('x y')
eq1 = x - y + 2
eq2 = 2*x + 3*y - 6
sol1 = solve((eq1, eq2), (x, y))
print("Vấn đề 1:", sol1)
# Vấn đề 2
z = symbols('z')
eq3 = x - y - 2
eq4 = 2*x - y + z - 3
eq5 = x + y + z - 6
sol2 = solve((eq3, eq4, eq5), (x, y, z))
print("Vấn đề 2:", sol2)
# Vấn đề 3
a, b, c = symbols('a b c')
eq6 = a + b + c - 4
eq7 = 4*a + 2*b + c - 3
eq8 = 9*a + 3*b + c - 4
sol3 = solve((eq6, eq7, eq8), (a, b, c))
print("Vấn đề 3:", sol3)
# Vấn đề 4
x = symbols('x')
f = (x * (x - 3)) / ((x - 1)**2 * (x + 2))
integral = integrate(f, (x, 0, 1))
print("Vấn đề 4:", integral)

Vấn đề 1: {x: 0, y: 2}
Vấn đề 2: {x: 7, y: 5, z: -6}
Vấn đề 3: {a: 1, b: -4, c: 7}
Vấn đề 4: -oo + I*pi/9


In [3]:
#Câu 3
import numpy as np

# Định nghĩa ma trận A
A = np.array([[1, 1],
              [1, 0]])

def matrix_inverse(A):
    det = A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]
    if det == 0:
        raise ValueError("Ma trận không khả nghịch")
    return (1 / det) * np.array([[A[1, 1], -A[0, 1]],
                                 [-A[1, 0], A[0, 0]]])
def matrix_power(A, k):
    if k == 0:
        return np.eye(2)
    result = A
    for _ in range(k - 1):
        result = np.dot(result, A)
    return result
k = 2
A_inv = matrix_inverse(A)
A_inv_k = matrix_power(A_inv, k)
print(f"Ma trận A:\n{A}")
print(f"Ma trận nghịch đảo A^(-1):\n{A_inv}")
print(f"Ma trận (A^(-1))^({k}):\n{A_inv_k}")
A_k = matrix_power(A, k)
print(f"Ma trận A^({k}):\n{A_k}")

def fibonacci(n):
    fib = [0, 1]
    for i in range(2, n + 1):
        fib.append(fib[i-1] + fib[i-2])
    return fib

fib_seq = fibonacci(k + 2)
print(f"Dãy Fibonacci đến F_{k+1}: {fib_seq}")
print(f"Phần tử của A^({k}) so sánh với Fibonacci: "
      f"F_{k+1}={fib_seq[k+1]}, F_{k}={fib_seq[k]}, F_{k-1}={fib_seq[k-1]}")

Ma trận A:
[[1 1]
 [1 0]]
Ma trận nghịch đảo A^(-1):
[[-0.  1.]
 [ 1. -1.]]
Ma trận (A^(-1))^(2):
[[ 1. -1.]
 [-1.  2.]]
Ma trận A^(2):
[[2 1]
 [1 1]]
Dãy Fibonacci đến F_3: [0, 1, 1, 2, 3]
Phần tử của A^(2) so sánh với Fibonacci: F_3=2, F_2=1, F_1=1


In [4]:
# Một số hàm về xử lý vector với Python
#Hàm scale
def scale(a, v):
    return [a * vi for vi in v]

v = [3, 5, 7]
scale(10, v)

[30, 50, 70]

In [5]:
#Hàm sumvector
def sumvector(v, w):
    return [vi + wi for (vi, wi) in zip(v, w)]

v = [3, 5, 7]
w = [2, 4, 6]
sumvector(v, w)

[5, 9, 13]

In [6]:
#Hàm dovector
def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])

v = [3, 5, 7]
w = [2, 4, 6]
dotvector(v, w)

68

In [7]:
#Hàm lenvector
def lenvector(v):
    return dotvector(v, v)

w = [2, 4, 6]
lenvector(w)

56

In [13]:
#Phân loại tuyến tính
import numpy as np

# Phân loại nhị phân
scores_binary = np.array([-1, 1, 2, -3, 5, -4])
print("scores:", scores_binary)
print("scores >= 0:", scores_binary >= 0)
print("scores < 0:", scores_binary < 0)
# Sử dụng default='' để đảm bảo kiểu dữ liệu chuỗi
print("np.select([scores >= 0, scores < 0], ['so duong', 'so am']):",
      np.select([scores >= 0, scores < 0], ['so duong', 'so am'], default=''))

# Phân loại thành 3 loại
scores_ternary = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print("\nscores:", scores_ternary)
# Sử dụng default='' cho phân loại 3 loại
print("np.select([scores > 0, scores == 0, scores < 0], ['so duong', 'so 0', 'so am']):",
      np.select([scores > 0, scores == 0, scores < 0], ['so duong', 'so 0', 'so am'], default=''))

scores: [-1  1  2 -3  5 -4]
scores >= 0: [False  True  True False  True False]
scores < 0: [ True False False  True False  True]
np.select([scores >= 0, scores < 0], ['so duong', 'so am']): ['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']

scores: [-1  1  2  0 -3  5  0 -4]
np.select([scores > 0, scores == 0, scores < 0], ['so duong', 'so 0', 'so am']): ['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


In [ ]:
#Cơ bản về xử lý ma trận
import numpy as np
from scipy import linalg, sparse

# STT 3 & 4: Tạo và in ma trận D
D = np.mat([[3, 4], [5, 6]])
print("D:\n", D)

# STT 5 & 6: Tạo và in ma trận C (kích thước 5x7, ngẫu nhiên)
C = np.mat(np.random.random((5, 7)))
print("C:\n", C)

# STT 7 & 8: Tạo và in ma trận A (kích thước 2x2, ngẫu nhiên)
A = np.mat(np.random.random((2, 2)))
print("A:\n", A)

# STT 9 & 10 & 11 & 12: Tạo mảng b, chuyển thành ma trận B và in
b = np.array([(1+5j, 2j, 3j), (4, 5, 6)])
print("b:\n", b)
B = np.asmatrix(b)
print("B:\n", B)

# STT 13: Chuyển vị ma trận A
print("A.T:\n", A.T)

# STT 14 & 15: Ma trận nghịch đảo của A
print("A.I:\n", A.I)
print("linalg.inv(A):\n", linalg.inv(A))

# STT 16 & 17 & 18: Ma trận tam giác dưới
M = np.array([[-1, 3, 2], [0, 2, 1], [1, 5, -2]])
M_lower = np.tril(M)
print("M_lower:\n", M_lower)

# STT 19 & 20 & 21: Ma trận tam giác trên
M = np.array([[-1, 3, 2], [0, 2, 1], [1, 5, -2]])
M_upper = np.triu(M)
print("M_upper:\n", M_upper)

# STT 22 & 23 & 24 & 25 & 26: Vector và ma trận đường chéo
M = np.array([[-1, 3, 2], [0, 2, 1], [1, 5, -2]])
v_diag = np.diag(M)
print("v_diag:\n", v_diag)
M_diag = np.diag(v_diag)
print("M_diag:\n", M_diag)

In [17]:
import numpy as np

# Xây dựng ma trận A 6x6
A = np.reshape(np.arange(36.0), (6, 6))
print("A:\n", A)

# Ma trận đơn vị 6x6
I6 = np.identity(6)
print("I6:\n", I6)

# Kích thước và đường chéo
print("A.size:", A.size)
print("np.matrix.diagonal(A):", np.matrix.diagonal(A))

# Cộng ma trận
A = A + I6
print("A = A + I6:\n", A)

# Tích với vector
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print("C = A.dot(vecB):\n", C)

# Ma trận D 2x6
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print("D:\n", D)

# Tích A và D^T (chuyển vị D để phù hợp kích thước)
D_transpose = D.T  # Chuyển D từ 2x6 thành 6x2
E = A.dot(D_transpose)
print("E = A.dot(D^T):\n", E)

# Ma trận F 6x2
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0.], [5., 1.], [6., 0.]])
print("F:\n", F)

# Tích A và F
G = A.dot(F)
print("G = A.dot(F):\n", G)

# Ma trận nghịch đảo
print("np.linalg.inv(A):\n", np.linalg.inv(A))

# Kiểm tra nghịch đảo của nghịch đảo
print("np.linalg.inv(np.linalg.inv(A)):\n", np.linalg.inv(np.linalg.inv(A)))

A:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
I6:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
A.size: 36
np.matrix.diagonal(A): [ 0.  7. 14. 21. 28. 35.]
A = A + I6:
 [[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]
C = A.dot(vecB):
 [ 71. 198. 325. 452. 579. 706.]
D:
 [[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
E = A.dot(D^T):
 [[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]
F:
 [[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
G = A.dot(F):
 [[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]
np.linalg.inv(A):
 [[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695

In [18]:
#4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng
import numpy as np
A = np.array([[1, 1], [1, 0]])
b = np.array([1, 0])
n = 10
for i in range(n):
    b = A.dot(b)
    print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [24]:
# Nếu bạn dùng Google Colab thì thường không cần dòng này, vì sympy đã có sẵn
!pip install sympy

import numpy as np
import sympy as sp
from sympy import Eq
# Phần 1: Tính 11 số Fibonacci đầu tiên
print("Dãy Fibonacci (F_n+1, F_n):")
A = np.array([[1, 1], [1, 0]])
b = np.array([1, 0])
n = 10
for i in range(n):
    b = A.dot(b)
    print(b)

# Phần 2: Giải hệ phương trình bằng SymPy
# Khai báo các biến
x1, x2, x3, x4 = sp.symbols('x1 x2 x3 x4')
# Thiết lập các phương trình
pt1 = Eq(x4 + 610, 450 + x1)   # x4 + 610 = 450 + x1
pt2 = Eq(x1 + 400, x2 + 640)   # x1 + 400 = x2 + 640
pt3 = Eq(x2 + 600, x3)         # x2 + 600 = x3
pt4 = Eq(x3, x4 + 520)         # x3 = x4 + 520
# Giải hệ phương trình
nghiem = sp.solve((pt1, pt2, pt3, pt4), (x1, x2, x3, x4))
print("\nNghiệm SymPy:", nghiem)
# Phần 3: Giải bằng ma trận tuyến tính (NumPy)
# Tạo ma trận hệ số A và vector hằng số b
A_mat = np.array([
    [-1,  0,  0,  1],  # từ pt1: -x1 + x4 = -160
    [ 1, -1,  0,  0],  # từ pt2: x1 - x2 = 240
    [ 0,  1, -1,  0],  # từ pt3: x2 - x3 = -600
    [ 0,  0,  1, -1]   # từ pt4: x3 - x4 = 520
])
b_vec = np.array([-160, 240, -600, 520])

# Giải hệ bằng lstsq (do ma trận A suy biến)
x, residuals, rank, s = np.linalg.lstsq(A_mat, b_vec, rcond=None)
print("\nNghiệm x (x1, x2, x3, x4):", x)


Dãy Fibonacci (F_n+1, F_n):
[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]

Nghiệm SymPy: {x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

Nghiệm x (x1, x2, x3, x4): [  10. -230.  370. -150.]
