In [4]:
#bài 1
import numpy as np

A = np.array([[2, 1, 3],
              [0, 4, 2],
              [1, 0, 5]])

det_A = np.linalg.det(A)
if abs(det_A) > 1e-10:
    A_nghich_dao = np.linalg.inv(A)
    print("Ma trận A khả nghịch với định thức:", det_A)
else:
    print("Ma trận A không khả nghịch.")
    exit()

# b. Nhập họ tên hoặc mã số sinh viên
thong_tin = input("Nhập họ tên hoặc mã số sinh viên: ")
# Chuyển đổi thành số (tổng mã ASCII của mỗi nhóm 3 ký tự)
do_dai = len(thong_tin)
so_ky_tu_can_bo_sung = (3 - (do_dai % 3)) % 3
thong_tin_bo_sung = thong_tin + " " * so_ky_tu_can_bo_sung
danh_sach_so = [sum(ord(ky_tu) for ky_tu in thong_tin_bo_sung[i:i+3]) for i in range(0, len(thong_tin_bo_sung), 3)]


while len(danh_sach_so) < 9:
    danh_sach_so.append(0)

ma_tran_thong_diep = np.array(danh_sach_so[:9]).reshape(3, 3)

# c. Mã hóa thông điệp
ma_tran_ma_hoa = np.dot(A, ma_tran_thong_diep) % 256

#d
ma_tran_giai_ma = np.dot(A_nghich_dao, ma_tran_ma_hoa) % 256
danh_sach_so_giai_ma = ma_tran_giai_ma.flatten()
thong_tin_giai_ma = ""
for so in danh_sach_so_giai_ma:
    if so != 0:
        thong_tin_giai_ma += chr(int(so) % 256)
thong_tin_giai_ma = thong_tin_giai_ma.strip()

print("Thông tin gốc:", thong_tin)
print("Ma trận đã mã hóa:\n", ma_tran_ma_hoa)
print("Thông tin giải mã:", thong_tin_giai_ma)

Ma trận A khả nghịch với định thức: 29.99999999999999
Nhập họ tên hoặc mã số sinh viên: le minh tam
Thông tin gốc: le minh tam
Ma trận đã mã hóa:
 [[208 136 248]
 [184   0   0]
 [241  68 252]]
Thông tin giải mã: CQî*"


In [8]:
#Bài 2
import numpy as np

# Hàm tính p_n và q_n từ danh sách a_i
def tinh_phan_so_lien_phan_so(danh_sach_a):
    # Khởi tạo ma trận ban đầu [p_n, p_{n-1}; q_n, q_{n-1}]
    ket_qua = np.array([[1, 0], [0, 1]], dtype=np.int64)

    # Nhân lần lượt với từng ma trận [a_i, 1; 1, 0]
    for a_i in danh_sach_a:
        ma_tran = np.array([[a_i, 1], [1, 0]], dtype=np.int64)
        ket_qua = np.dot(ket_qua, ma_tran)

    # Lấy p_n và q_n từ ma trận kết quả
    p_n = ket_qua[0, 0]  # Tử số
    q_n = ket_qua[1, 0]  # Mẫu số

    return p_n, q_n

# Nhập danh sách a_i từ người dùng
danh_sach_a = list(map(int, input("Nhập danh sách a_0, a_1, ..., a_n (cách nhau bởi dấu cách): ").split()))

# Tính p_n và q_n
p_n, q_n = tinh_phan_so_lien_phan_so(danh_sach_a)

# In kết quả
print(f"Phân số là: {p_n}/{q_n}")

Nhập danh sách a_0, a_1, ..., a_n (cách nhau bởi dấu cách): 1 2 3
Phân số là: 10/7


In [ ]:
# b chứng minh
#Bằng quy nạp toán học:
#Công thức đúng cho $ n = 0 $.
#Nếu đúng cho $ n = k $, thì đúng cho $ n = k+1 $.
#Do đó, công thức:
#$$\prod_{i=0}^{n} \begin{bmatrix} a_i & 1 \\ 1 & 0 \end{bmatrix} = \begin{bmatrix} p_n & p_{n-1} \\ q_n & q_{n-1} \end{bmatrix}$$
#đúng cho mọi $ n \geq 0 $. Điều này có nghĩa là tích các ma trận $ \begin{bmatrix} a_i & 1 \\ 1 & 0 \end{bmatrix} $ từ $ i = 0 $ đến $ n $ sẽ cho ra ma trận chứa tử số $ p_n $ và mẫu số $ q_n $ của liên phân số, cùng với các giá trị trước đó $ p_{n-1} $ và $ q_{n-1} $.

In [11]:
#Một số phép xử lý ma trận của NumPy và Scip
from scipy import linalg
import numpy as np

a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]])
A = np.matrix(np.random.random((2, 2)))  # Đã sửa trước đó
B = np.asmatrix(b)
C = np.asmatrix(np.random.random((10, 5)))  # Thay np.mat bằng np.asmatrix
D = np.asmatrix([[4, 3], [2, 6]])  # Thay np.mat bằng np.asmatrix
F = np.eye(3, k=1)

print(A)

[[0.21075207 0.1191824 ]
 [0.26210649 0.49455862]]


In [12]:
#Giả các phương trình tuyến tình
from scipy import linalg
import numpy as np

a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])  # Số phức, kích thước 2x3
# Giả định A là ma trận 2x2 ngẫu nhiên, ví dụ: A = [[0.1, 0.2], [0.3, 0.4]]
A = np.matrix([[0.1, 0.2], [0.3, 0.4]])
B = np.asmatrix(b)  # Ma trận 2x3 số phức
C = np.asmatrix(np.random.random((10, 5)))  # Không dùng trực tiếp
D = np.asmatrix([[4, 3], [2, 6]])  # Ma trận 2x2
F = np.eye(3, k=1)  # Ma trận 3x3, [[0, 1, 0], [0, 0, 1], [0, 0, 0]]

In [13]:
import numpy as np

# Tính ma trận A và các lũy thừa của nó
print("Ma trận A và các lũy thừa của nó:")
A = np.array([[0,1], [1,0]])
print("A =")
print(A)
print("---")

# Tính lần thứ nhất (A^2)
temp = A.dot(A)
print("A^2 =")
print(temp)
print("---")

# Tính A^3 đến A^6
k = 6
for i in range(k-1):
    temp = temp.dot(A)
    print(f"A^{i+3} =")
    print(temp)
    print("---")

print("Nhận xét: Ma trận A lặp lại chu kỳ 2 bước: A^2=I, A^3=A, A^4=I,... Không hội tụ về 1 ma trận duy nhất.")

print("\n" + "="*50 + "\n")

# Tính ma trận B và các lũy thừa của nó
print("Ma trận B và các lũy thừa của nó:")
B = np.array([[0,-1], [-1,0]])
print("B =")
print(B)
print("---")

# Tính lần thứ nhất (B^2)
temp = B.dot(B)
print("B^2 =")
print(temp)
print("---")

# Tính B^3 đến B^5
k = 5
for i in range(k-1):
    temp = temp.dot(B)
    print(f"B^{i+3} =")
    print(temp)
    print("---")

print("Nhận xét: Ma trận B cũng lặp lại chu kỳ 2 bước: B^2=I, B^3=B, B^4=I,... Không hội tụ về 1 ma trận duy nhất.")


Ma trận A và các lũy thừa của nó:
A =
[[0 1]
 [1 0]]
---
A^2 =
[[1 0]
 [0 1]]
---
A^3 =
[[0 1]
 [1 0]]
---
A^4 =
[[1 0]
 [0 1]]
---
A^5 =
[[0 1]
 [1 0]]
---
A^6 =
[[1 0]
 [0 1]]
---
A^7 =
[[0 1]
 [1 0]]
---
Nhận xét: Ma trận A lặp lại chu kỳ 2 bước: A^2=I, A^3=A, A^4=I,... Không hội tụ về 1 ma trận duy nhất.


Ma trận B và các lũy thừa của nó:
B =
[[ 0 -1]
 [-1  0]]
---
B^2 =
[[1 0]
 [0 1]]
---
B^3 =
[[ 0 -1]
 [-1  0]]
---
B^4 =
[[1 0]
 [0 1]]
---
B^5 =
[[ 0 -1]
 [-1  0]]
---
B^6 =
[[1 0]
 [0 1]]
---
Nhận xét: Ma trận B cũng lặp lại chu kỳ 2 bước: B^2=I, B^3=B, B^4=I,... Không hội tụ về 1 ma trận duy nhất.


In [24]:
import numpy as np

# Khởi tạo ma trận C
C = np.array([
    [1, 0, 0],
    [0, 0.5, 1],
    [0, 0, 0.5]
])
print("Ma trận C =")
print(C)
print("---")

# Tính toán lần thứ nhất (C^2)
temp = C.dot(C)
print("C^2 =")
print(temp)
print("---")

# Tính lũy thừa bậc 1000 (C^1000)
k = 1000
for i in range(k-1):
    temp = temp.dot(C)
print(f"C^{k} =")
print(temp)


# Thực hiện thêm 1000 lần tích nữa (C^2000)
k = 1000
for i in range(k-1):
    temp = temp.dot(C)
print(f"C^{2*k} =")
print(temp)



Ma trận C =
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
---
C^2 =
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
---
C^1000 =
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
C^2000 =
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
import numpy as np

# Khởi tạo ma trận M
M = np.array([
    [0.8, 0.3],
    [0.2, 0.7]
])
print("Ma trận M =")
print(M)
print("---")

# Tính M2 = M.M
MM = M.dot(M)
print("M^2 =")
print(MM)
print("---")

# Tính M3 = M.M2
MM = M.dot(MM)
print("M^3 =")
print(MM)
print("---")

# Tính M^100
for i in range(100):
    MM = MM.dot(M)
print("M^103 =")
print(MM)


Ma trận M =
[[0.8 0.3]
 [0.2 0.7]]
---
M^2 =
[[0.7  0.45]
 [0.3  0.55]]
---
M^3 =
[[0.65  0.525]
 [0.35  0.475]]
---
M^103 =
[[0.6 0.6]
 [0.4 0.4]]


In [22]:
import numpy as np
from scipy import linalg

# Khởi tạo ma trận M
M = np.array([
    [0.8, 0.3],
    [0.2, 0.7]
])
print("Ma trận M =")
print(M)
print("---")

# Phân tách LU
P, L, U = linalg.lu(M)

print("Ma trận P (Permutation matrix):")
print(P)
print("---")

print("Ma trận L (Lower triangular matrix):")
print(L)
print("---")

print("Ma trận U (Upper triangular matrix):")
print(U)
print("---")

# Kiểm tra lại phép nhân L.dot(U)
print("L.dot(U) =")
print(L.dot(U))
print("---")

# Kiểm tra lại toàn bộ: P.dot(M) có bằng L.dot(U)?
print("P.dot(M) =")
print(P.dot(M))



Ma trận M =
[[0.8 0.3]
 [0.2 0.7]]
---
Ma trận P (Permutation matrix):
[[1. 0.]
 [0. 1.]]
---
Ma trận L (Lower triangular matrix):
[[1.   0.  ]
 [0.25 1.  ]]
---
Ma trận U (Upper triangular matrix):
[[0.8   0.3  ]
 [0.    0.625]]
---
L.dot(U) =
[[0.8 0.3]
 [0.2 0.7]]
---
P.dot(M) =
[[0.8 0.3]
 [0.2 0.7]]


In [21]:
import numpy as np

# Ma trận A ban đầu
A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])
print("Ma trận A =")
print(A)
print("---")

# Tính A^2
temp = A.dot(A)
print("A^2 =")
print(temp)
print("---")

print("Nhận xét A^2: Số bước đi 2 bước giữa các đỉnh được liệt kê ở đây. Các phần tử khác 0 cho thấy có đường đi 2 bước giữa các đỉnh.")
print("---")

# Tính A^3
temp = temp.dot(A)
print("A^3 =")
print(temp)



Ma trận A =
[[0 1 0 1]
 [0 0 1 0]
 [1 0 0 1]
 [1 1 0 0]]
---
A^2 =
[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
---
Nhận xét A^2: Số bước đi 2 bước giữa các đỉnh được liệt kê ở đây. Các phần tử khác 0 cho thấy có đường đi 2 bước giữa các đỉnh.
---
A^3 =
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [20]:
import numpy as np

# Ma trận A ban đầu
A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])
print("Ma trận A:")
print(A)
print("---")

# Tính tổng các lũy thừa từ 1 đến k=3
sumA = A.copy()     # ban đầu là A
temp = A.dot(A)     # tính A^2

k = 3
sumA = sumA + temp  # cộng thêm A^2

for i in range(1, k-1):  # i=1 => chỉ tính thêm A^3
    temp = temp.dot(A)   # tính A^3
    sumA = sumA + temp   # cộng vào tổng

print("Ma trận temp (A^3):")
print(temp)
print("---")

print("Tổng các lũy thừa từ A đến A^3 (sumA):")
print(sumA)



Ma trận A:
[[0 1 0 1]
 [0 0 1 0]
 [1 0 0 1]
 [1 1 0 0]]
---
Ma trận temp (A^3):
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
---
Tổng các lũy thừa từ A đến A^3 (sumA):
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
