In [1]:
#Bài 1
import numpy as np

def get_minor_matrix(matrix, i, j):
    """Lấy ma trận con bằng cách xóa hàng i và cột j"""
    return np.delete(np.delete(matrix, i, axis=0), j, axis=1)

def cofactor_matrix(matrix):
    """Tính ma trận hệ số kép (cofactor matrix)"""
    n = matrix.shape[0]
    cofactor = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            minor = get_minor_matrix(matrix, i, j)
            cofactor[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)

    return cofactor

def adjoint_matrix(matrix):
    """Tính ma trận liên hợp (adjoint matrix)"""
    return np.transpose(cofactor_matrix(matrix))

# Hàm kiểm tra và ví dụ sử dụng
def main():
    # Ma trận ví dụ 3x3
    A = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

    print("Ma trận A:")
    print(A)

    # Tính ma trận hệ số kép
    cofactor = cofactor_matrix(A)
    print("\nMa trận hệ số kép (Cofactor matrix):")
    print(cofactor)

    # Tính ma trận liên hợp
    adj = adjoint_matrix(A)
    print("\nMa trận liên hợp (Adjoint matrix):")
    print(adj)

if __name__ == "__main__":
    main()

Ma trận A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Ma trận hệ số kép (Cofactor matrix):
[[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]

Ma trận liên hợp (Adjoint matrix):
[[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]


In [4]:
!pip install sympy
from sympy import symbols, solve, Eq

x, y, a, b, c = symbols('x y a b c')

def find_circle_equation(x1, y1, x2, y2, x3, y3):
    # Tạo hệ phương trình
    eq1 = Eq(x1**2 + y1**2 + a*x1 + b*y1 + c, 0)
    eq2 = Eq(x2**2 + y2**2 + a*x2 + b*y2 + c, 0)
    eq3 = Eq(x3**2 + y3**2 + a*x3 + b*y3 + c, 0)

    # Giải hệ phương trình
    solution = solve((eq1, eq2, eq3), (a, b, c))

    return solution

x1, y1 = 0, 0
x2, y2 = 1, 1
x3, y3 = 2, 0

# Tìm phương trình
result = find_circle_equation(x1, y1, x2, y2, x3, y3)


if result and isinstance(result, dict):
    a, b, c = result[a], result[b], result[c]
    print(f"Phương trình đường tròn: x^2 + y^2 + {a}*x + {b}*y + {c} = 0")
elif result and len(result) > 0:
    a, b, c = result[0][a], result[0][b], result[0][c]
    print(f"Phương trình đường tròn: x^2 + y^2 + {a}*x + {b}*y + {c} = 0")
else:
    print("Không tìm thấy đường tròn hợp lệ qua 3 điểm (có thể 3 điểm thẳng hàng).")


Phương trình đường tròn: x^2 + y^2 + -2*x + 0*y + 0 = 0


In [5]:
#Định thức và các tính chất
import numpy as np

def sgn_by_def(sigma):
    """Tính dấu của hoán vị sigma dựa trên số hoán vị nghịch."""
    n = len(sigma)
    inversions = 0
    for i in range(n):
        for j in range(i + 1, n):
            if sigma[i] > sigma[j]:
                inversions += 1
    return 1 if inversions % 2 == 0 else -1

# Ví dụ 1
n = 4
X = np.array(range(1, n + 1))
sigma = np.array([4, 3, 2, 1])
print("sgn_by_def([4, 3, 2, 1]):", sgn_by_def(sigma))

# Ví dụ 2
sigma = np.array([1, 2, 3, 4])
print("sgn_by_def([1, 2, 3, 4]):", sgn_by_def(sigma))

# Ví dụ 3
sigma = np.array([4, 3, 2, 1])
print("sgn_by_def([4, 3, 2, 1]):", sgn_by_def(sigma))

sgn_by_def([4, 3, 2, 1]): 1
sgn_by_def([1, 2, 3, 4]): 1
sgn_by_def([4, 3, 2, 1]): 1


In [6]:
#Đoạn code 1
import numpy as np
from itertools import permutations

# Hàm tính dấu của hoán vị sign of permutation
def sgn_by_def(sigma):
    """Tính dấu của hoán vị sigma dựa trên số hoán vị nghịch."""
    n = len(sigma)
    inversions = 0
    for i in range(n):
        for j in range(i + 1, n):
            if sigma[i] > sigma[j]:
                inversions += 1
    return 1 if inversions % 2 == 0 else -1


def phatsinh_dinhtheuc(n):
    X = [i for i in range(1, n+1)]
    Sn = list(permutations(X))
    dinhtthuc = ""

    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = ""

        # Gán giá trị cho sigma theo chỉ số
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product + "a" + str(i) + str(sn.index(i)+1)

        # Tính dấu của hoán vị và thêm vào product
        dau = sgn_by_def(sigma)
        if (dau == 1):
            product = " + " + product
        else:
            product = " - " + product

        dinhtthuc = dinhtthuc + product

    return dinhtthuc

print("Kết quả cho n = 2:")
result_n2 = phatsinh_dinhtheuc(2)
print(result_n2 + " '")

print("\nKết quả cho n = 3:")
result_n3 = phatsinh_dinhtheuc(3)
print(result_n3 + " '")

Kết quả cho n = 2:
 + a11a22 - a12a21 '

Kết quả cho n = 3:
 + a11a22a33 - a11a23a32 - a12a21a33 + a13a21a32 + a12a23a31 - a13a22a31 '


In [8]:
!pip install numpy  # Đảm bảo NumPy được cài đặt
!pip install itertools  # Đảm bảo itertools được sử dụng (thực tế đã có trong Python)
from itertools import permutations
import numpy as np

def sgn_by_def(sigma):
    """Tính dấu của hoán vị sigma dựa trên số hoán vị nghịch."""
    n = len(sigma)
    inversions = 0
    for i in range(n):
        for j in range(i + 1, n):
            if sigma[i] > sigma[j]:
                inversions += 1
    return 1 if inversions % 2 == 0 else -1

def tinhtoan_dinhtheuc(A):
    n = int(np.sqrt(A.size))
    X = list(range(1, n + 1))
    Sn = list(permutations(X))
    dinhtthuc = 0

    for sigma in Sn:
        product = 1

        for i in range(n):
            j = sigma[i] - 1
            product *= A[i, j]

        dau = sgn_by_def(sigma)
        if dau == 1:
            dinhtthuc += product
        else:
            dinhtthuc += product * (-1)

    return dinhtthuc

A = np.array([[3, 5, -8],
              [4, -12, -1],
              [2, 5, 3]])
print("Ma trận A:")
print(A)
print("\nĐịnh thức của ma trận A:", tinhtoan_dinhtheuc(A))

ERROR: Could not find a version that satisfies the requirement itertools (from versions: none)
ERROR: No matching distribution found for itertools
Ma trận A:
[[  3   5  -8]
 [  4 -12  -1]
 [  2   5   3]]

Định thức của ma trận A: -515


In [9]:
import numpy as np
from itertools import permutations


def sgn_by_def(sigma):
    n = len(sigma)
    inversions = 0
    for i in range(n):
        for j in range(i + 1, n):
            if sigma[i] > sigma[j]:
                inversions += 1
    return 1 if inversions % 2 == 0 else -1

def tinhtoan_dinhtheuc(A):
    n = int(np.sqrt(A.size))
    X = list(range(1, n + 1))
    Sn = list(permutations(X))
    dinhtthuc = 0

    for sigma in Sn:
        product = 1
        for i in range(n):
            j = sigma[i] - 1
            product *= A[i, j]
        dau = sgn_by_def(sigma)
        if dau == 1:
            dinhtthuc += product
        else:
            dinhtthuc += product * (-1)
    return dinhtthuc

# Khai báo ma trận hệ số A và vectơ vế phải B
A = np.array([[2, -3, 1],
              [2, -2, 1],
              [3, -4, 4]])

B = np.array([1, 3, 2])

# Tạo ma trận detX (thay cột x bằng B)
detX = np.array([[1, -3, 1],
                 [3, -2, 1],
                 [2, -4, 4]])

# Tạo ma trận detY (thay cột y bằng B)
detY = np.array([[2, 1, 1],
                 [2, 3, 1],
                 [3, 2, 4]])

# Tạo ma trận detZ (thay cột z bằng B)
detZ = np.array([[2, -3, 1],
                 [2, -2, 3],
                 [3, -4, 2]])


det = tinhtoan_dinhtheuc(A)
detX = tinhtoan_dinhtheuc(detX)
detY = tinhtoan_dinhtheuc(detY)
detZ = tinhtoan_dinhtheuc(detZ)


x, y, z = detX/det, detY/det, detZ/det


print("Nghiệm: ", "x=", x, "y=", y, "z =", z)

Nghiệm:  x= 3.6 y= 2.0 z = -0.2


In [10]:
#Tính diện tích tam giác
import sympy as sp
TG = sp.Matrix([[1, 0, 1],
                [4, 3, 1],
                [2, 2, 1]])

det_TG = TG.det()
dien_tich = sp.Abs(det_TG) / 2

print("Kết quả diện tích tam giác là:", dien_tich)

Kết quả diện tích tam giác là: 3/2


In [11]:
from sympy import *
x, y, z = symbols('x y z')
MP = Matrix([[x, y, z, 1],
             [-1, 3, 2, 1],
             [0, 1, 0, 1],
             [-2, 0, 1, 1]])

det_MP = MP.det()
print("Định thức của ma trận MP:", det_MP)

P1 = Matrix([-1, 3, 2])
P2 = Matrix([0, 1, 0])
P3 = Matrix([-2, 0, 1])

# Vectơ pháp tuyến (tích vectơ của P1P2 và P1P3)
v1 = P2 - P1
v2 = P3 - P1
normal = v1.cross(v2)

a, b, c = normal[0], normal[1], normal[2]
d = -(a * P1[0] + b * P1[1] + c * P1[2])

equation = f"{a}x + {b}y + {c}z + {d} = 0"
print("\nPhương trình mặt phẳng đi qua các điểm (-1, 3, 2), (0, 1, 0), (-2, 0, 1):")
print(equation)

Định thức của ma trận MP: -4*x + 3*y - 5*z - 3

Phương trình mặt phẳng đi qua các điểm (-1, 3, 2), (0, 1, 0), (-2, 0, 1):
-4x + 3y + -5z + -3 = 0
