In [3]:
# Import thư viện NumPy
import numpy as np
def print_array_info(name, arr):
    print(f"\nMảng {name}:")
    print(arr)
    print(f"Kích thước: {arr.shape}, Kiểu dữ liệu: {arr.dtype}")
    print(f"Địa chỉ bộ nhớ: {id(arr)}")

def check_memory_sharing(arr1, arr2):
    print(f"\nHai mảng có chia sẻ bộ nhớ không? {np.may_share_memory(arr1, arr2)}")
print("=== Minh họa các dạng sao chép mảng ===")
A = np.array([[1, 2], [3, 4]])
print_array_info("A (mảng gốc)", A)

# 1. Tạo tham chiếu (B = A)
print("\n1. Tạo tham chiếu (B = A)")
B = A
print_array_info("B (tham chiếu)", B)
check_memory_sharing(A, B)
# Thay đổi B, kiểm tra ảnh hưởng đến A
B[0, 0] = 99
print("\nSau khi thay đổi B[0,0] = 99:")
print_array_info("A", A)
print_array_info("B", B)
A = np.array([[1, 2], [3, 4]])
# 2. Tạo bản sao hoàn chỉnh (B = np.copy(A) và B = A.copy())
print("\n2. Tạo bản sao hoàn chỉnh")
B = np.copy(A)  # Cách 1
C = A.copy()    # Cách 2
print_array_info("B (np.copy)", B)
print_array_info("C (A.copy)", C)
check_memory_sharing(A, B)
# Thay đổi B, kiểm tra A
B[0, 0] = 88
print("\nSau khi thay đổi B[0,0] = 88:")
print_array_info("A", A)
print_array_info("B", B)
print("\n3. Tạo bản sao bằng np.copyto")
# Khởi tạo mảng D
D = np.array([[1, 2], [3, 4]])
print_array_info("D", D)
# Trường hợp 1: Thử np.copyto khi E chưa khởi tạo
print("\nTrường hợp 1: np.copyto(E, D) khi E chưa khởi tạo")
try:
    np.copyto(E, D)
except NameError as e:
    print(f"Lỗi: {e}")
print("\nTrường hợp 2: np.copyto(E, D) khi E đã khởi tạo")
E = np.array([[1, 2], [3, 5]])
print_array_info("E (trước khi sao chép)", E)
np.copyto(E, D)
print_array_info("E (sau khi sao chép)", E)
print_array_info("D", D)
check_memory_sharing(D, E)
print("\n=== Minh họa sao chép với B[:] = A ===")
B = np.zeros((2, 2), dtype=int)
print_array_info("B (trước khi sao chép)", B)
B[:] = A
print_array_info("B (sau khi sao chép)", B)
check_memory_sharing(A, B)

# Kết luận
print("Kết luận")
print("1. B = A: Tạo tham chiếu, chia sẻ bộ nhớ, thay đổi B ảnh hưởng A.")
print("2. B = np.copy(A) hoặc B = A.copy(): Tạo bản sao độc lập, không chia sẻ bộ nhớ.")
print("3. np.copyto(B, A) hoặc B[:] = A: Sao chép dữ liệu vào B đã khởi tạo, không chia sẻ bộ nhớ.")

=== Minh họa các dạng sao chép mảng ===

Mảng A (mảng gốc):
[[1 2]
 [3 4]]
Kích thước: (2, 2), Kiểu dữ liệu: int64
Địa chỉ bộ nhớ: 131949837432080

1. Tạo tham chiếu (B = A)

Mảng B (tham chiếu):
[[1 2]
 [3 4]]
Kích thước: (2, 2), Kiểu dữ liệu: int64
Địa chỉ bộ nhớ: 131949837432080

Hai mảng có chia sẻ bộ nhớ không? True

Sau khi thay đổi B[0,0] = 99:

Mảng A:
[[99  2]
 [ 3  4]]
Kích thước: (2, 2), Kiểu dữ liệu: int64
Địa chỉ bộ nhớ: 131949837432080

Mảng B:
[[99  2]
 [ 3  4]]
Kích thước: (2, 2), Kiểu dữ liệu: int64
Địa chỉ bộ nhớ: 131949837432080

2. Tạo bản sao hoàn chỉnh

Mảng B (np.copy):
[[1 2]
 [3 4]]
Kích thước: (2, 2), Kiểu dữ liệu: int64
Địa chỉ bộ nhớ: 131949847454768

Mảng C (A.copy):
[[1 2]
 [3 4]]
Kích thước: (2, 2), Kiểu dữ liệu: int64
Địa chỉ bộ nhớ: 131949837432080

Hai mảng có chia sẻ bộ nhớ không? False

Sau khi thay đổi B[0,0] = 88:

Mảng A:
[[1 2]
 [3 4]]
Kích thước: (2, 2), Kiểu dữ liệu: int64
Địa chỉ bộ nhớ: 131949847454000

Mảng B:
[[88  2]
 [ 3  4]]
Kích thước: 

In [4]:
from numpy import matlib
import numpy as np
def print_matrix_info(name, matrix):
    print(f"\nMa trận {name}:")
    print(matrix)
    print(f"Kích thước: {matrix.shape}, Kiểu dữ liệu: {matrix.dtype}")
    print(f"Kiểu đối tượng: {type(matrix)}")
print("=== Ma trận đơn vị G = matlib.identity(5) ===")
G = matlib.identity(5)
print_matrix_info("G", G)
print("\n=== Ma trận H = matlib.randn(3,2) ===")
H = matlib.randn(3, 2)
print_matrix_info("H", H)
print(" Ma trận K = matlib.zeros([4,4]) ")
K = matlib.zeros([4, 4])
print_matrix_info("K", K)
print("\n=== Minh họa thêm các hàm khác trong matlib ===")
print("\nMa trận ones (2x3):")
M = matlib.ones((2, 3))
print_matrix_info("M", M)
print("\nMa trận eye (3x4, k=1):")
N = matlib.eye(3, 4, k=1, dtype=float)
print_matrix_info("N", N)
print("\nMa trận rand (2x2):")
P = matlib.rand(2, 2)
print_matrix_info("P", P)

=== Ma trận đơn vị G = matlib.identity(5) ===

Ma trận G:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Kích thước: (5, 5), Kiểu dữ liệu: float64
Kiểu đối tượng: <class 'numpy.matrix'>

=== Ma trận H = matlib.randn(3,2) ===

Ma trận H:
[[-1.26812464  0.38458332]
 [-0.99535128 -0.70846314]
 [ 0.03946003  0.66962808]]
Kích thước: (3, 2), Kiểu dữ liệu: float64
Kiểu đối tượng: <class 'numpy.matrix'>
 Ma trận K = matlib.zeros([4,4]) 

Ma trận K:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Kích thước: (4, 4), Kiểu dữ liệu: float64
Kiểu đối tượng: <class 'numpy.matrix'>

=== Minh họa thêm các hàm khác trong matlib ===

Ma trận ones (2x3):

Ma trận M:
[[1. 1. 1.]
 [1. 1. 1.]]
Kích thước: (2, 3), Kiểu dữ liệu: float64
Kiểu đối tượng: <class 'numpy.matrix'>

Ma trận eye (3x4, k=1):

Ma trận N:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Kích thước: (3, 4), Kiểu dữ liệu: float64
Kiểu đối tượng: <class 'numpy.matrix'>

Ma trận rand (2

In [6]:
import numpy as np

def calculate_pi(c):
    print(f"\nTính số Pi với dãy c: {c}")
    M = np.array([[1, 2], [3, 4]], dtype=float)

    for i in range(len(c)):
        ci = np.array([[1, 1], [1, 0]], dtype=float)
        ci[0, 0] = c[i]

        if i == 0:
            M = ci
        else:
            M = M @ ci

    pi_approx = M[0, 0] / M[1, 0]
    print(f"Ma trận M cuối cùng:\n{M}")
    print(f"Giá trị Pi tính được: {pi_approx}")
    print(f"Sai số so với np.pi ({np.pi}): {abs(pi_approx - np.pi)}")
    return pi_approx

c_cases = [
    [3, 7, 15, 1],
    [3, 7, 15, 1, 292, 1, 1, 1],
    [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
]

for c in c_cases:
    calculate_pi(c)

print(f"\nGiá trị Pi thực (np.pi): {np.pi}")


Tính số Pi với dãy c: [3, 7, 15, 1]
Ma trận M cuối cùng:
[[355. 333.]
 [113. 106.]]
Giá trị Pi tính được: 3.1415929203539825
Sai số so với np.pi (3.141592653589793): 2.667641894049666e-07

Tính số Pi với dãy c: [3, 7, 15, 1, 292, 1, 1, 1]
Ma trận M cuối cùng:
[[312689. 208341.]
 [ 99532.  66317.]]
Giá trị Pi tính được: 3.1415926536189365
Sai số so với np.pi (3.141592653589793): 2.914335439641036e-11

Tính số Pi với dãy c: [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
Ma trận M cuối cùng:
[[1.65707065e+08 8.01438570e+07]
 [5.27461970e+07 2.55105820e+07]]
Giá trị Pi tính được: 3.1415926535897936
Sai số so với np.pi (3.141592653589793): 4.440892098500626e-16

Giá trị Pi thực (np.pi): 3.141592653589793


In [7]:
import numpy as np
X = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
Y = np.array([[0.8], [0.5], [0.2], [-0.1]])
XT = X.T
A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)
A = A1.dot(A2)
print(f"Phương trình đường thẳng: y = {A[0,0]:.1f}x + {A[1,0]:.1f}")

Phương trình đường thẳng: y = -0.3x + 0.8


In [8]:
#Câu 1
import numpy as np

X = np.array([[0, 1], [1, 1], [2, 1], [3, 1], [4, 1]])
Y = np.array([[10], [8], [7], [5], [2]])
XT = X.T

A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)

A = A1.dot(A2)
a, b = A[0, 0], A[1, 0]
print(f"Phương trình tuyến tính: y = {b:.1f} {a:+.1f}x")
print(f"Hệ số a (độ dốc): {a:.1f}")
print(f"Hệ số b (hệ số chặn): {b:.1f}")

Y_pred = X.dot(A)
error = np.sum((Y - Y_pred)**2)
print(f"Tổng bình phương sai số: {error:.2f}")

Phương trình tuyến tính: y = 10.2 -1.9x
Hệ số a (độ dốc): -1.9
Hệ số b (hệ số chặn): 10.2
Tổng bình phương sai số: 1.10
