In [2]:
#Câu 1
import numpy as np

print("=== Câu 1: Phép toán cơ bản trên vector và ma trận ===")
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
tong_AB = A + B
tich_2A_3B = 2 * A + 3 * B
print("a) Tổng A + B:", tong_AB)
print("Tích số 2A + 3B:", tich_2A_3B)
tich_vo_huong = np.dot(A, B)
cos_theta = tich_vo_huong / (np.linalg.norm(A) * np.linalg.norm(B))
theta_rad = np.arccos(np.clip(cos_theta, -1.0, 1.0))
theta_deg = np.degrees(theta_rad)
print("b) Tích vô hướng A . B:", tich_vo_huong)
print("Góc giữa hai vector (độ, làm tròn 3 chữ số):", round(theta_deg, 3))
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])
C_transpose = C.T
tich_CCt = np.dot(C, C_transpose)
print("c) Tích ma trận C * C^T:\n", tich_CCt)

=== Câu 1: Phép toán cơ bản trên vector và ma trận ===
a) Tổng A + B: [2 3 1 6]
Tích số 2A + 3B: [ 3 11  2 14]
b) Tích vô hướng A . B: -5
Góc giữa hai vector (độ, làm tròn 3 chữ số): 99.594
c) Tích ma trận C * C^T:
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [3]:
#Câu 2
import numpy as np
print("=== Câu 2: Nhân ma trận, định thức và hạng ma trận ===")
M = np.array([[2, -1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]])
N = np.array([[1, 3, -2, 0],
              [4, -1, 5, 2],
              [0, 2, 3, -1],
              [-3, 1, 0, 4]])
tich_MN = np.dot(M, N)
print("a) Tích ma trận M * N:\n", tich_MN)
try:
    det_M = np.linalg.det(M)
    print("b) Định thức của ma trận M:", det_M)
    if abs(det_M) < 1e-10:
        print("Ma trận M không khả nghịch (định thức gần 0).")
except np.linalg.LinAlgError:
    print("b) Không thể tính định thức vì ma trận M không vuông hoặc suy biến.")
hang_N = np.linalg.matrix_rank(N)
print("c) Hạng của ma trận N:", hang_N)

=== Câu 2: Nhân ma trận, định thức và hạng ma trận ===
a) Tích ma trận M * N:
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
b) Định thức của ma trận M: 409.00000000000017
c) Hạng của ma trận N: 4


In [5]:
#Câu 3
import numpy as np
print(" Câu 3: Nghịch đảo ma trận và giải hệ phương trình")
P = np.array([[3, -1, 0, 2],
              [1, 4, -2, 0],
              [0, 1, 5, -1],
              [2, 0, 1, 3]])
try:
    det_P = np.linalg.det(P)
    print("a) Định thức của ma trận P:", det_P)
    if abs(det_P) > 1e-10:
        P_inv = np.linalg.inv(P)
        print("Ma trận nghịch đảo của P:\n", P_inv)
    else:
        print("Ma trận P không khả nghịch (định thức gần 0).")
except np.linalg.LinAlgError:
    print("a) Không thể tính nghịch đảo vì ma trận P suy biến hoặc không vuông.")

A = P
b = np.array([6, 8, 3, 7])

try:
    x = np.linalg.solve(A, b)
    print("b) Nghiệm của hệ phương trình (x, y, z, w):", x)
except np.linalg.LinAlgError:
    print("b) Hệ phương trình không có nghiệm duy nhất hoặc ma trận A suy biến.")
if 'x' in locals():
    P_x = np.dot(P, x)
    print("c) Kiểm tra (P @ x):", P_x)
    print("Vector hạng số b:", b)
    if np.allclose(P_x, b, atol=1e-8):
        print("Nghiệm đúng (P @ x ≈ b).")
    else:
        print("Nghiệm không khớp với vector b.")

 Câu 3: Nghịch đảo ma trận và giải hệ phương trình
a) Định thức của ma trận P: 140.00000000000006
Ma trận nghịch đảo của P:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
b) Nghiệm của hệ phương trình (x, y, z, w): [2.         1.71428571 0.42857143 0.85714286]
c) Kiểm tra (P @ x): [6. 8. 3. 7.]
Vector hạng số b: [6 8 3 7]
Nghiệm đúng (P @ x ≈ b).


In [7]:
#câu 4
import numpy as np
print("Câu 4: Giá trị riêng, vector riêng và chuẩn hóa")
Q = np.array([[5, -2, 1],
              [0, 3, -1],
              [2, 0, 4]])
eigenvalues = np.linalg.eigvals(Q)
print("a) Các giá trị riêng của Q:", eigenvalues)
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("b) Các vector riêng (cột) tương ứng với giá trị riêng:")
for i in range(len(eigenvalues)):
    print(f"Vector riêng cho giá trị riêng {eigenvalues[i]}:\n", eigenvectors[:, i])
print("c) Các vector riêng được chuẩn hóa (độ dài = 1):")
for i in range(eigenvectors.shape[1]):
    vec = eigenvectors[:, i]
    norm_vec = vec / np.linalg.norm(vec)
    print(f"Vector riêng chuẩn hóa cho giá trị riêng {eigenvalues[i]}:\n", norm_vec)

Câu 4: Giá trị riêng, vector riêng và chuẩn hóa
a) Các giá trị riêng của Q: [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]
b) Các vector riêng (cột) tương ứng với giá trị riêng:
Vector riêng cho giá trị riêng (6.355301397608123+0j):
 [ 0.74846013+0.j -0.18941773+0.j  0.63555359+0.j]
Vector riêng cho giá trị riêng (2.822349301195943+1.0773038128499652j):
 [-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
Vector riêng cho giá trị riêng (2.822349301195943-1.0773038128499652j):
 [-0.37423006-0.34234215j  0.09470887-0.57433055j  0.63555359-0.j        ]
c) Các vector riêng được chuẩn hóa (độ dài = 1):
Vector riêng chuẩn hóa cho giá trị riêng (6.355301397608123+0j):
 [ 0.74846013+0.j -0.18941773+0.j  0.63555359+0.j]
Vector riêng chuẩn hóa cho giá trị riêng (2.822349301195943+1.0773038128499652j):
 [-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
Vector riêng chuẩn hóa cho giá trị riêng (2.822349301195943-1.0773038128499652j

In [8]:
import numpy as np

print(" Câu 5: Ứng dụng thuật toán - Hệ phương trình và phân tích ")
R = np.array([[4, -1, 2],
              [1, 3, -2],
              [0, 2, 5]])
b = np.array([12, 5, 9])
try:
    x = np.linalg.solve(R, b)
    print("a) Nghiệm của hệ phương trình (x):", x)
except np.linalg.LinAlgError:
    print("a) Hệ phương trình không có nghiệm duy nhất hoặc ma trận R suy biến.")
det_R = np.linalg.det(R)
print("b) Định thức của ma trận R:", det_R)
if abs(det_R) > 1e-10:
    R_inv = np.linalg.inv(R)
    print("Ma trận R khả nghịch. Ma trận nghịch đảo:\n", R_inv)
else:
    print("Ma trận R không khả nghịch (định thức gần 0).")
frobenius_norm = np.sqrt(np.sum(R ** 2))
print("c) Chuẩn Frobenius của ma trận R:", frobenius_norm)

 Câu 5: Ứng dụng thuật toán - Hệ phương trình và phân tích 
a) Nghiệm của hệ phương trình (x): [2.78823529 1.52941176 1.18823529]
b) Định thức của ma trận R: 85.00000000000001
Ma trận R khả nghịch. Ma trận nghịch đảo:
 [[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
c) Chuẩn Frobenius của ma trận R: 8.0
