In [1]:
#Câu 1
import numpy as np
A = np.array([-2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1], [0, 3, 4], [2, -1, 0]])
print("a) Tính tổng A + B và tích số 3A - 2B:")
print("A + B =", A + B)
print("3A - 2B =", 3*A - 2*B)
dot_product = np.dot(A, B)
magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)
cos_theta = dot_product / (magnitude_A * magnitude_B)
theta = np.arccos(np.clip(cos_theta, -1, 1)) * 180 / np.pi
print("\nb) Tích vô hướng A · B =", dot_product)
print("Góc giữa hai vector (độ) =", theta)
C_transpose = C.T
C_T_C = np.dot(C_transpose, C)
print("\nc) Tích ma trận C^T * C:")
print(C_T_C)

a) Tính tổng A + B và tích số 3A - 2B:
A + B = [-1  3  1  5]
3A - 2B = [ -8 -11  13 -10]

b) Tích vô hướng A · B = -12
Góc giữa hai vector (độ) = 118.22051205340371

c) Tích ma trận C^T * C:
[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [2]:
#Câu 2
import numpy as np
M = np.array([[1, 2, 3, 0], [4, 5, 6, 1], [7, 8, 9, 2], [0, 1, 0, 0]])
N = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
print("a) Tích ma trận M × N:")
M_N = np.dot(M, N)
print(M_N)
det_M = np.linalg.det(M)
print("\nb) Định thức của ma trận M:", det_M)
rank_N = np.linalg.matrix_rank(N)
print("\nc) Hạng của ma trận N:", rank_N)

a) Tích ma trận M × N:
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [  4   5   6   7]]

b) Định thức của ma trận M: 1.3322676295501906e-15

c) Hạng của ma trận N: 2


In [3]:
#Câu 3
import numpy as np
P = np.array([[2, 1, 0, 1], [0, 3, 1, -1], [1, 0, 4, 2], [0, 1, 0, 3]])
P_inv = np.linalg.inv(P)
print("a) Ma trận nghịch đảo của P:")
print(P_inv)
b = np.array([4, 7, 9, 5])
solution = np.linalg.solve(P, b)
print("\nb) Giải hệ phương trình: [x, y, z, w] =", solution)
check = np.dot(P, solution)
print("\nc) Kiểm tra: P * nghiệm =", check)

a) Ma trận nghịch đảo của P:
[[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

b) Giải hệ phương trình: [x, y, z, w] = [0.46511628 2.10465116 1.65116279 0.96511628]

c) Kiểm tra: P * nghiệm = [4. 7. 9. 5.]


In [4]:
#Câu 4
import numpy as np
Q = np.array([[1, -1, 0], [3, 1, -2], [0, 1, 2]])
eigenvalues = np.linalg.eigvals(Q)
print("a) Giá trị riêng của Q:", eigenvalues)
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("\nb) Vector riêng tương ứng:")
for i in range(len(eigenvalues)):
    print(f"Giá trị riêng {eigenvalues[i]}: {eigenvectors[:, i]}")
normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("\nc) Vector riêng chuẩn hóa:")
for i in range(len(eigenvalues)):
    print(f"Vector riêng {eigenvalues[i]} chuẩn hóa: {normalized_eigenvectors[:, i]}")

a) Giá trị riêng của Q: [1.18531916+2.175406j 1.18531916-2.175406j 1.62936168+0.j      ]

b) Vector riêng tương ứng:
Giá trị riêng (1.1853191597919253+2.175405997365573j): [ 0.03291514-0.38638094j -0.84663523+0.j          0.12782157+0.34131626j]
Giá trị riêng (1.1853191597919253-2.175405997365573j): [ 0.03291514+0.38638094j -0.84663523-0.j          0.12782157-0.34131626j]
Giá trị riêng (1.6293616804161477+0j): [ 0.48339855+0.j -0.30423252+0.j  0.82083397+0.j]

c) Vector riêng chuẩn hóa:
Vector riêng (1.1853191597919253+2.175405997365573j) chuẩn hóa: [ 0.03291514-0.38638094j -0.84663523+0.j          0.12782157+0.34131626j]
Vector riêng (1.1853191597919253-2.175405997365573j) chuẩn hóa: [ 0.03291514+0.38638094j -0.84663523+0.j          0.12782157-0.34131626j]
Vector riêng (1.6293616804161477+0j) chuẩn hóa: [ 0.48339855+0.j -0.30423252+0.j  0.82083397+0.j]


In [5]:
#Câu 5
import numpy as np
R = np.array([[1, -2, 3], [0, 1, 4], [-1, 1, -1]])
b = np.array([10, 8, 7])
z = np.linalg.solve(R, b)
print("a) Giải hệ phương trình Rz = b: z =", z)
det_R = np.linalg.det(R)
is_invertible = det_R != 0
print("\nb) Ma trận R có khả nghịch không? (True/False):", is_invertible)
if is_invertible:
    print("Nghịch đảo của ma trận R:")
    R_inv = np.linalg.inv(R)
    print(R_inv)
frobenius_norm = np.linalg.norm(R, 'fro')
print("\nc) Chuỗi Frobenius của ma trận R:", frobenius_norm)

a) Giải hệ phương trình Rz = b: z = [-19.83333333  -8.66666667   4.16666667]

b) Ma trận R có khả nghịch không? (True/False): True
Nghịch đảo của ma trận R:
[[-0.83333333  0.16666667 -1.83333333]
 [-0.66666667  0.33333333 -0.66666667]
 [ 0.16666667  0.16666667  0.16666667]]

c) Chuỗi Frobenius của ma trận R: 5.830951894845301
