In [1]:
#bài 1
import numpy as np
import math
a = np.array([1, 2, 3])
mag_a = np.sqrt(a.dot(a))
print("Lựa chọn a:", mag_a)
mag_b = np.sqrt(a @ a)
print("Lựa chọn b:", mag_b)
mag_c = np.sqrt(np.inner(a, a))
print("Lựa chọn c:", mag_c)
mag_d = lambda x: math.sqrt(sum(i**2 for i in x))
print("Lựa chọn d:", mag_d(a))

Lựa chọn a: 3.7416573867739413
Lựa chọn b: 3.7416573867739413
Lựa chọn c: 3.7416573867739413
Lựa chọn d: 3.7416573867739413


In [2]:
#bài 2
import numpy as np
u = np.array([1, 2])
v = np.array([4, 6])
distance = np.sqrt(np.sum((u - v) ** 2))
print("Khoảng cách giữa u và v:", distance)
u = np.array([1, 0])
v = np.array([1, 1])
dot_product = np.dot(u, v)
norm_u = np.sqrt(np.sum(u ** 2))
norm_v = np.sqrt(np.sum(v ** 2))
cos_theta = dot_product / (norm_u * norm_v)
theta = np.arccos(cos_theta) * 180 / np.pi
print("Góc giữa u và v (độ):", theta)
u = np.array([2, 2])
v = np.array([1, 0])
dot_uv = np.dot(u, v)
dot_vv = np.dot(v, v)
projection = (dot_uv / dot_vv) * v
print("Phép chiếu trực giao của u lên v:", projection)


Khoảng cách giữa u và v: 5.0
Góc giữa u và v (độ): 45.00000000000001
Phép chiếu trực giao của u lên v: [2. 0.]


In [3]:
#1.2.Tích vô hướng, trực giao và ứng dụng
import numpy as np
from scipy import linalg
import math
# Định nghĩa vector a và b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Tích vô hướng với np.inner và np.dot
tich_inner = np.inner(a, b)
print("Tích vô hướng (np.inner):", tich_inner)
tich_dot = np.dot(a, b)
print("Tích vô hướng (np.dot):", tich_dot)
# Chuẩn vector a = [1, 2, -3]
a = np.array([1, 2, -3])
# Chuẩn 2
norm_2_np = np.linalg.norm(a, 2)
print("Chuẩn 2 (np.linalg.norm):", norm_2_np)
norm_2_scipy = linalg.norm(a)
print("Chuẩn 2 (scipy.linalg.norm):", norm_2_scipy)
# Chuẩn 1
norm_1_np = np.linalg.norm(a, 1)
print("Chuẩn 1 (np.linalg.norm):", norm_1_np)
norm_1_scipy = linalg.norm(a, 1)
print("Chuẩn 1 (scipy.linalg.norm):", norm_1_scipy)
# Hàm tự định nghĩa để tính chuẩn bậc k
def chuan(vector, k):
    return sum(abs(x) ** k for x in vector) ** (1/k) if k > 0 else 0
# Kiểm tra các chuẩn với hàm chuan
print("Chuẩn 1 (chuan):", chuan(a, 1))
print("Chuẩn 2 (chuan):", chuan(a, 2))
print("Chuẩn 3 (chuan):", chuan(a, 3))
print("Chuẩn 1000 (chuan):", chuan(a, 1000))
# So sánh với np.linalg.norm
print("Chuẩn 1 (np.linalg.norm):", np.linalg.norm(a, 1))
print("Chuẩn 2 (np.linalg.norm):", np.linalg.norm(a, 2))
print("Chuẩn 3 (np.linalg.norm):", np.linalg.norm(a, 3))
print("Chuẩn 1000 (np.linalg.norm):", np.linalg.norm(a, 1000))
# So sánh với scipy.linalg.norm
print("Chuẩn 100 (scipy.linalg.norm):", linalg.norm(a, 100))
print("Chuẩn 1000 (scipy.linalg.norm):", linalg.norm(a, 1000))
# Lỗi khi k quá lớn (thử nghiệm, tùy môi trường)
try:
    print("Chuẩn 10000 (np.linalg.norm):", np.linalg.norm(a, 10000))
except Exception as e:
    print("Lỗi:", str(e))
# Khoảng cách giữa a và b
distance = np.linalg.norm(a - b)
print("Khoảng cách giữa a và b:", distance)
# Góc giữa a và b
dot_product = np.dot(a, b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
cos_theta = dot_product / (norm_a * norm_b)
theta = np.arccos(cos_theta) * 180 / np.pi
print("Góc giữa a và b (độ):", theta)
# Phép chiếu trực giao của a lên b
dot_ab = np.dot(a, b)
dot_bb = np.dot(b, b)
projection = (dot_ab / dot_bb) * b
print("Phép chiếu trực giao của a lên b:", projection)

Tích vô hướng (np.inner): 32
Tích vô hướng (np.dot): 32
Chuẩn 2 (np.linalg.norm): 3.7416573867739413
Chuẩn 2 (scipy.linalg.norm): 3.7416573867739413
Chuẩn 1 (np.linalg.norm): 6.0
Chuẩn 1 (scipy.linalg.norm): 6.0
Chuẩn 1 (chuan): 6.0
Chuẩn 2 (chuan): 3.7416573867739413
Chuẩn 3 (chuan): 3.3019272488946263
Chuẩn 1000 (chuan): 1.0442214818467515
Chuẩn 1 (np.linalg.norm): 6.0
Chuẩn 2 (np.linalg.norm): 3.7416573867739413
Chuẩn 3 (np.linalg.norm): 3.3019272488946263
Chuẩn 1000 (np.linalg.norm): inf
Chuẩn 100 (scipy.linalg.norm): 3.0
Chuẩn 1000 (scipy.linalg.norm): inf
Chuẩn 10000 (np.linalg.norm): inf
Khoảng cách giữa a và b: 9.9498743710662
Góc giữa a và b (độ): 96.99767003015255
Phép chiếu trực giao của a lên b: [-0.20779221 -0.25974026 -0.31168831]


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [4]:
#Tổ hợp tuyến tính
import numpy as np
m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])
M = np.array([v1, v2, v3, v4])
MT = M.transpose()
print(MT)
v = (1.0 / m) * MT.dot(mi)
print(v)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
[1.3 0.9 0. ]


In [5]:
#Tri riêng, vector riêng của ma trận và ứng dụng
import numpy as np
from numpy.linalg import matrix_power
# Khai báo ma trận A
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])
# Khai báo vector v0
v0 = np.array([0.95, 0.05])
# Tính vector A^100 (sử dụng matrix_power)
A100 = matrix_power(A, 100)
# Tính vector v100 = A^100 * v0
v100 = A100.dot(v0)
print("Ma trận A^100:")
print(A100)
print("Vector trạng thái sau 100 tuần (v100):")
print(v100)

Ma trận A^100:
[[0.98550725 0.9855069 ]
 [0.01449275 0.0144931 ]]
Vector trạng thái sau 100 tuần (v100):
[0.98550723 0.01449277]


In [6]:
#3.2.Trị riêng và vector riêng của ma trận
import numpy as np

# Khai báo ma trận A
A = np.array([[1, 6],
              [5, 2]])
# Khai báo vector u (giả sử u là vector cột [6, 0] hoặc [0, 6], ta thử [6, 0] để kiểm tra)
u = np.array([6, 0])
# Chứng minh Au = -4u
Au = A.dot(u)
lambda_u = -4 * u
print("A * u =", Au)
print("-4 * u =", lambda_u)
print("Kiểm tra Au = -4u:", np.allclose(Au, lambda_u))  # Kiểm tra xem Au có gần bằng -4u không

A * u = [ 6 30]
-4 * u = [-24   0]
Kiểm tra Au = -4u: False


In [12]:
#3.3.Ứng dụng của trị riêng và vector riêng
import numpy as np
from numpy import linalg as LA

# Khai báo ma trận A, D, P
A = np.array([[2, 3],
              [3, -6]])
D = np.array([[-7, 0],
              [0, 3]])
P = np.array([[-1.0/3, 3],
              [1, 1]])
# Tính ma trận nghịch đảo P^(-1)
P1 = LA.inv(P)
print("P^(-1):")
print(P1)
# Kiểm tra A * P = P * D
AP = A.dot(P)
PD = P.dot(D)
print("A * P:")
print(AP)
print("P * D:")
print(PD)
print("Kiểm tra A * P ≈ P * D:", np.allclose(AP, PD))
# Tính A^1000 sử dụng matrix_power (đã cho kết quả)
A1000_direct = LA.matrix_power(A, 1000)
print("A^1000 (sử dụng matrix_power):")
print(A1000_direct)
# Thử tính D^1000 an toàn hơn bằng cách sử dụng log hoặc matrix_power trên D
try:
    D1000 = np.diag([(-7)**1000, 3**1000])
    A1000_chinh = P @ D1000 @ P1
    print("A^1000 (phương pháp chéo hóa):")
    print(A1000_chinh)
except OverflowError:
    print("Lỗi tràn số khi tính D^1000 trực tiếp. Sử dụng matrix_power thay thế.")
# Kiểm tra lại vector riêng và giá trị riêng để xác nhận
eigenvalues, eigenvectors = LA.eig(A)
P_correct = eigenvectors
D_correct = np.diag(eigenvalues)
print("Giá trị riêng (eigenvalues):", eigenvalues)
print("Vector riêng (eigenvectors):")
print(P_correct)

P^(-1):
[[-0.3  0.9]
 [ 0.3  0.1]]
A * P:
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
P * D:
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
Kiểm tra A * P ≈ P * D: True
A^1000 (sử dụng matrix_power):
[[-7877686877730399439  5349495576147410896]
 [ 5349495576147410896  8601565042059090865]]
Lỗi tràn số khi tính D^1000 trực tiếp. Sử dụng matrix_power thay thế.
Giá trị riêng (eigenvalues): [ 3. -7.]
Vector riêng (eigenvectors):
[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]
